let data = [
  {
    id: 0,
    floor: 'LowFloor',
    roomType: '스탠다드',
    name: '슈페리어 더블 룸',
    bedType: '더블',
    people: '1~2명',
    roomSize: '25㎡ ~ 27㎡',
    link: 'superior-double',
    reName: 'superior_double',
    checkInOutTime: '15시/12시',
    roomImage: 'rooms/standard/superiorDouble/room1.jpg',
    price: '120,000',
  },
  {
    id: 1,
    floor: 'LowFloor',
    roomType: '스탠다드',
    name: '슈페리어 트윈 룸',
    bedType: '더블/트윈',
    people: '1~2명',
    roomSize: '25㎡ ~ 27㎡',
    roomImage: 'rooms/standard/superiorDouble/room1.jpg',
    link: 'superior-twin',
    reName: 'superior_twin',
    price: '130,000',
    checkInOutTime: '15시/12시',
  },
  {
    id: 2,
    floor: 'HighFloor',
    roomType: '부티크',
    name: '부티크 트윈 룸',
    bedType: '더블/트윈',
    people: '2~3명',
    roomSize: '30㎡ ~ 31㎡',
    view: '시티',
    checkInOutTime: '15시/12시',
    roomImage: 'rooms/boutique/boutiqueTwin/room1.jpg',
    link: 'boutique-twin',
    reName: 'boutique_twin',
    price: '180,000',
  },
  {
    id: 3,
    floor: 'HighFloor',
    roomType: '부티크',
    name: '부티크 패밀리 룸',
    bedType: '더블/트윈',
    people: '3~4명',
    roomSize: '32㎡ ~ 33㎡',
    view: '시티',
    checkInOutTime: '15시/12시',
    roomImage: 'rooms/boutique/boutiqueFamily/room1.jpg',
    link: 'boutique-family',
    reName: 'boutique_family',
    price: '210,000',
  },
  {
    id: 4,
    floor: 'HighFloor',
    roomType: '디럭스',
    name: '디럭스 트윈 룸',
    bedType: '더블/트윈',
    people: '3~4명',
    roomSize: '34㎡ ~ 35㎡',
    view: '시티',
    checkInOutTime: '15시/12시',
    roomImage: 'rooms/deluxe/deluxeTwin/room1.jpg',
    link: 'deluxe-twin',
    reName: 'deluxe_twin',
    price: '220,000',
  },
  {
    id: 5,
    floor: 'HighFloor',
    roomType: '디럭스',
    name: '디럭스 스위트 룸',
    bedType: '더블/트윈',
    people: '3~4명',
    roomSize: '35㎡ ~ 37㎡',
    checkInOutTime: '15시/12시',
    view: '시티',
    roomImage: 'rooms/deluxe/deluxeSuite/room1.jpg',
    link: 'deluxe-suite',
    reName: 'deluxe_suite',
    price: '240,000',
  },
  {
    id: 6,
    floor: 'HighFloor',
    roomType: '스위트',
    name: '스위트 프리미어 룸',
    bedType: '더블/트윈',
    people: '4~6명',
    roomSize: '40㎡ ~ 43㎡',
    view: '시티',
    checkInOutTime: '15시/12시',
    roomImage: 'rooms/suite/suitePremier/room4.jpg',
    link: 'suite-premier',
    reName: 'suite_premier',
    price: '300,000',
  },
  {
    id: 7,
    floor: 'HighFloor',
    roomType: '스위트',
    name: '로얄 스위트 룸',
    bedType: '더블/트윈',
    people: '2~3명',
    roomSize: '42㎡ ~ 45㎡',
    view: '시티',
    checkInOutTime: '15시/12시',
    roomImage: 'rooms/suite/royalSuite/room1.jpg',
    link: 'royal-suite',
    reName: 'royal_suite',
    price: '320,000',
  },
];

export let Lists = JSON.stringify(data);
