export const PRODUCT = {
  necklace: [
    { label: '18K 목걸이', value: '' },
    { label: '18K 팬던트', value: '' },
    { label: '18K 체인목걸이', value: '' },
    { label: '24K 순금목걸이', value: '' },
    { label: '탄생석/원석', value: '' },
    { label: '별자리/룬 목걸이', value: '' },
    { label: '이니셜 목걸이', value: '' },
    { label: '진주 목걸이', value: '' },
    { label: '실버 목걸이', value: '' },
    { label: '롱 목걸이', value: '' },
    { label: '1부 다이아몬드 목걸이', value: '' },
    { label: '2부 다이아몬드 목걸이', value: '' },
    { label: '5부 다이아몬드 목걸이', value: '' },
    { label: '블루 다이아몬드 목걸이', value: '' },
  ],
  earring: [
    { label: '피어싱 귀걸이', value: '' },
    { label: '침형 귀걸이', value: '' },
    { label: '롱스타일 귀걸이', value: '' },
    { label: '링/파이프 귀걸이', value: '' },
    { label: '원터치 귀걸이', value: '' },
    { label: '드롭형 귀걸이', value: '' },
    { label: '탄생석 귀걸이', value: '' },
    { label: '이니셜 귀걸이', value: '' },
    { label: '귀찌', value: '' },
    { label: '다이아몬드 귀걸이', value: '' },
    { label: '진주 귀걸이', value: '' },
    { label: '실버 귀걸이', value: '' },
  ],
  gold: [
    { label: '순금 돌선물', value: '' },
    { label: '순금 목걸이', value: '' },
    { label: '순금 팔찌', value: '' },
    { label: '순금 카드상패', value: '' },
    { label: '순금 기념품', value: '' },
  ]
}