import Head from 'next/head'
import MainContainer from 'container/MainContainer';

export default function Home() {
  return (
    <>
      <Head>
        <title>쇼핑몰</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer />
    </>
  )
}
