import { ReactComponent as bed } from "./bed.svg";
import { ReactComponent as ovalCheck } from "./ovalCheck.svg";
import { ReactComponent as human } from "./human.svg";
import { ReactComponent as cart } from "./cart.svg";
import { ReactComponent as search } from "./search.svg";
import { ReactComponent as bookmark } from "./bookmark.svg";
import { ReactComponent as arrowTop } from "./arrowTop.svg";
import { ReactComponent as arrowBottom } from "./arrowBottom.svg";
import { ReactComponent as close } from "./close.svg";
import { ReactComponent as arrowLeft } from "./arrowLeft.svg";
// import { ReactComponent as necklace } from "./necklace.svg";
import { ReactComponent as heart } from "./heart.svg";
import { ReactComponent as BigArrowLeft } from "./BigArrowLeft.svg";
import { ReactComponent as cartAdd } from "./cartAdd.svg";
import { ReactComponent as plus } from "./plus.svg";
import { ReactComponent as minus } from "./minus.svg";
import { ReactComponent as info } from "./info.svg";
import { ReactComponent as closeSmall } from "./closeSmall.svg";
import { ReactComponent as user } from "./user.svg";
import { ReactComponent as home } from "./home.svg";
import { ReactComponent as arrowNoTailTop } from "./arrowNoTailTop.svg";
import { ReactComponent as arrowNoTailBottom } from "./arrowNoTailBottom.svg";
import { ReactComponent as trashCan } from "./trashCan.svg";
import { ReactComponent as check } from "./check.svg";
import { ReactComponent as location } from "./location.svg";
import { ReactComponent as userNot } from "./userNot.svg";
import { ReactComponent as coin } from "./coin.svg";
import { ReactComponent as warning } from "./warning.svg";
import { ReactComponent as back } from "./back.svg";
import { ReactComponent as menu } from "./menu.svg";
import { ReactComponent as menu2 } from "./menu2.svg";
import { ReactComponent as pencil } from "./pencil.svg";
import { ReactComponent as circlePlus } from "./circlePlus.svg";
import { ReactComponent as circleCheck } from "./circleCheck.svg";
import { ReactComponent as note } from "./note.svg";
import { ReactComponent as arrowRight } from "./arrowRight.svg";

export { bed, ovalCheck, human, cart, search, bookmark, arrowTop, arrowBottom, arrowLeft, close, heart, BigArrowLeft, cartAdd, plus, minus, info, closeSmall, user, home, arrowNoTailBottom, arrowNoTailTop, trashCan, check, location, userNot, coin, warning, back, menu, menu2, pencil, circlePlus, circleCheck, note, arrowRight };
